// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client"
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client"

const tables = [
  {
    name: "guestbook",
    checkConstraints: {},
    foreignKeys: {},
    primaryKey: ["id"],
    uniqueConstraints: {},
    columns: [
      {
        name: "body",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "createdAt",
        type: "timestamp without time zone",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "createdBy",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "email",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "id",
        type: "int",
        notNull: true,
        unique: true,
        defaultValue:
          "nextval('bb_0um3vngc3t29d8145u753s8dc4_n9nt8o.guestbook_id_seq'::regclass)",
        comment: "",
      },
    ],
  },
] as const

export type SchemaTables = typeof tables
export type InferredTypes = SchemaInference<SchemaTables>

export type Guestbook = InferredTypes["guestbook"]
export type GuestbookRecord = Guestbook & XataRecord

export type DatabaseSchema = {
  guestbook: GuestbookRecord
}

const DatabaseClient = buildClient()

const defaultOptions = {
  databaseURL: "https://Nazar-s-workspace-n9nt8o.eu-central-1.xata.sh/db/site",
}

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables)
  }
}

let instance: XataClient | undefined = undefined

export const getXataClient = () => {
  if (instance) return instance

  instance = new XataClient({
    apiKey: "xau_BbxSX8HMFUOps0AT0zaGLfOsMHntL7Zu",
    branch: "main",
  })
  return instance
}
